### ISSUE TITLE
Invalid handle.  Not initialized or points to a deleted object. (3135)

### ISSUE THREAD

**Issue by c3rberus** [progress/iceberg#18]
Updating iceberg to latest March release and running oemanager status is not working, it is returning:

```
Buildfile: /usr3/wrk/traininga/utils/oemanager.xml

status:
     [echo] Code Release: 2023-04-23T17:24:41.290
     [echo]
     [echo] DLC Home: /usr1/dlc
     [echo] OpenEdge Version: 12.2.11
   [PCTRun] Starting output to file: status_traininga_2023-04-23T17_33_39.797-07_00.txt ...
   [PCTRun]
   [PCTRun] Utility Runtime: 12.2.11.0.1427
   [PCTRun] Report Executed: 2023-04-23T17:33:39.798-07:00
   [PCTRun]  PASOE Instance: http://localhost:17160
   [PCTRun] Invalid handle.  Not initialized or points to a deleted object. (3135)
   [PCTRun]
   [PCTRun] Manager Properties
   [PCTRun]
   [PCTRun] No MSAgents running
   [PCTRun]
   [PCTRun] Session Manager Metrics (Not Enabled)
   [PCTRun]
   [PCTRun] Client HTTP Sessions: 0
   [PCTRun]

BUILD SUCCESSFUL
```

Reverting back to an older build of iceberg (version before utils.zip deployment to PAS instance), I don't run into the same issue.

Not sure why this is happening, appreciate any help. would like to keep my local iceberg instance in sync with latest from this repo.

**Comment by DustinGrau-PSC** [comment]
You are correct, the userid and password must be explicitly supplied as these cannot be decrypted from any files in the instance, and the ablapp must specified as we cannot infer what you wish to monitor. The instance should either be stated if running against a remote instance, otherwise it will be detected when deployed into a PAS instance's CATALINA_BASE location.

After deploying the utilities, did you modify the `oemanager.properties` file to supply defaults where necessary for these parameters? Can you provide some insight into how you had deployed the tools and executed commands?

**Comment by DustinGrau-PSC** [comment]
I've found that the invalid handle error is a result of (obviously) pointing to an incorrect or non-existent PAS instance, though it can also present when the PAS instance is not running as expected. I'll be making some modifications to better handle that situation and offer a more useful error message.

**Comment by DustinGrau-PSC** [comment]
The next release will contain improved documentation and adjusts the code to better report when the remote server is not available due to common reasons (bad credentials, not running, etc).
