### ISSUE TITLE
Can we link the Agent Manager AgentSessionId and Session Manager BrokerSessionId when running status option?

### ISSUE THREAD

**Issue by c3rberus** [progress/iceberg#24]
This is more of an enhancement suggestion than an issue/bug.

Using the APSV adapter (state-free) in PASOE, if we are dealing with stuck ABL session and need to terminate them (trimsingle), we need to pass in the AgentSessionId.

Looking at the status output, it would be very useful to have the AgentSessionId somewhere with the Client HTTP Sessions output, that area has all the information (proc and IP) one would need to quickly identify the bad program but only from Session Manager perspective. See [Screenshot](https://ibb.co/Bt6KxKP).

I know we can use the "stacks" option, and that prints both the AgentSessionId and BrokerSessionId, it would be great if we could somehow link the AgentSessionId and BrokerSessionId on the "status" output.

Not sure if this request would work well across all the different adapter types (we only use APSV), feel free to close out if does not fit within the scope of how the status output was designed to be used as.

**Comment by DustinGrau-PSC** [comment]
So there are 2 aspects to this request. First, we can only interpret what is returned from the underlying statistics/metrics data. If the information is not included then either 1) there's no direct correlation available or 2) the data was simply not captured at the level you wanted. The only solution to the data display would be to make a product request to adjust the returned data, then we would be able to correlate the values and display them together. Having this request show a paper trail direct from end-users helps add a priority to the request, rather than my requesting it internally.

Second, and related to the reason for your request, terminating an Agent-Session should not be done if you have a stuck ABL session. Terminating the client session is the proper action as it will terminate the associated context--which in this case should be the Agent-Session. Terminating only the Agent-Session can still leave the client session lingering, or worse if that's a bound APSV session.
